### ISSUE TITLE
ALS Kalipo WIl IK een draaiend, geconfigureerd en stabiel netwerk.

### ISSUE THREAD

**Issue by Armaniimus** [Kalipo-BV/kalipo-core#796]
ALS Kalipo WIl IK een draaiend, geconfigureerd en stabiel netwerk, ZODAT de gebouwde applicatie door Kalipo gehost kan worden.

# Acceptance criteria
- [ ] Er is een draaiend netwerk
- [ ] Het netwerk is geconfigureerd
- [ ] Het netwerk is stabiel

# DoR
*Een user story voldoet aan de DoR wanneer deze voldoet aan:*
- [x] Er is een front-end ontwikkel omgeving beschikbaar
- [x] Er is een remote development omgeving als backend
- [x] Er is toegang tot de repository.
- [x] De userstory is aan een persoon geassigned

# DoD
*Een user story voldoet aan de DoD wanneer deze voldoet aan:*
- [ ] De stijl van Kalipo
- [ ] Gereviewd door de productowner(Peter) en voldoet aan acceptatiecriteria
- [ ] Er is een spellingscontrole gedaan
- [ ] Er zijn peer-reviews geweest
- [ ] Getest (Unit Test)
- [ ] Gedocumenteerd 

# Deliverables
- [ ] Inventariseren Lisk document
- [ ] Main Branche draaien
- [ ] Hardenend Node
